import {
  MessagesSquare,
  MessageCircle,
  Mail,
  Phone,
  Clock,
  Calendar,
  CheckSquare,
  CheckCircle2,
  Check,
  X,
  Package,
  TrendingUp,
  Download,
  ShieldCheck,
  Lock,
  Handshake,
  Image as ImageIcon,
  FileText,
  Palette,
  Globe,
  Scale,
  Star,
  Info,
  Users,
  Zap,
  Heart,
  Rocket,
  Target,
  Award,
  BookOpen,
  Lightbulb,
  Briefcase,
  CreditCard,
  Bell,
  Settings,
  ThumbsUp,
  Sparkles,
  Flag,
  Gift,
  type LucideIcon,
} from "lucide-react";

/**
 * Curated icon registry for the Welcome Kit builder. Keys are stable strings
 * persisted in the kit document (NOT component names) so the icon set can be
 * extended without breaking stored content. Shared by the renderer and the
 * builder's icon picker.
 */
export const ICON_MAP: Record<string, LucideIcon> = {
  messages: MessagesSquare,
  message: MessageCircle,
  mail: Mail,
  phone: Phone,
  clock: Clock,
  calendar: Calendar,
  checkSquare: CheckSquare,
  checkCircle: CheckCircle2,
  check: Check,
  x: X,
  package: Package,
  trending: TrendingUp,
  download: Download,
  shield: ShieldCheck,
  lock: Lock,
  handshake: Handshake,
  image: ImageIcon,
  file: FileText,
  palette: Palette,
  globe: Globe,
  scale: Scale,
  star: Star,
  info: Info,
  users: Users,
  zap: Zap,
  heart: Heart,
  rocket: Rocket,
  target: Target,
  award: Award,
  book: BookOpen,
  lightbulb: Lightbulb,
  briefcase: Briefcase,
  creditCard: CreditCard,
  bell: Bell,
  settings: Settings,
  thumbsUp: ThumbsUp,
  sparkles: Sparkles,
  flag: Flag,
  gift: Gift,
};

export const DEFAULT_ICON = "star";

/** Resolve an icon key to its component, falling back to the default. */
export function resolveIcon(key: string | undefined | null): LucideIcon {
  if (key && ICON_MAP[key]) return ICON_MAP[key];
  return ICON_MAP[DEFAULT_ICON];
}

/** Ordered options for the picker (label is human-readable). */
export const ICON_OPTIONS: { key: string; label: string }[] = [
  { key: "messages", label: "Messages" },
  { key: "message", label: "Chat bubble" },
  { key: "mail", label: "Mail" },
  { key: "phone", label: "Phone" },
  { key: "clock", label: "Clock" },
  { key: "calendar", label: "Calendar" },
  { key: "checkSquare", label: "Check square" },
  { key: "checkCircle", label: "Check circle" },
  { key: "check", label: "Check" },
  { key: "x", label: "Cross" },
  { key: "package", label: "Package" },
  { key: "trending", label: "Trending up" },
  { key: "download", label: "Download" },
  { key: "shield", label: "Shield" },
  { key: "lock", label: "Lock" },
  { key: "handshake", label: "Handshake" },
  { key: "image", label: "Image" },
  { key: "file", label: "Document" },
  { key: "palette", label: "Palette" },
  { key: "globe", label: "Globe" },
  { key: "scale", label: "Scale" },
  { key: "star", label: "Star" },
  { key: "info", label: "Info" },
  { key: "users", label: "Users" },
  { key: "zap", label: "Lightning" },
  { key: "heart", label: "Heart" },
  { key: "rocket", label: "Rocket" },
  { key: "target", label: "Target" },
  { key: "award", label: "Award" },
  { key: "book", label: "Book" },
  { key: "lightbulb", label: "Lightbulb" },
  { key: "briefcase", label: "Briefcase" },
  { key: "creditCard", label: "Credit card" },
  { key: "bell", label: "Bell" },
  { key: "settings", label: "Settings" },
  { key: "thumbsUp", label: "Thumbs up" },
  { key: "sparkles", label: "Sparkles" },
  { key: "flag", label: "Flag" },
  { key: "gift", label: "Gift" },
];
